apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmek12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmek12
  template:
    metadata:
      labels:
        app: lmek12
    spec:
      containers:
      - image: okteto.dev/lmek12:latest
        name: lmek12
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "639e8c55-057a-49df-b5a6-1553336a73bd"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "639e8c55-057a-49df-b5a6-1553336a73bd"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
