apiVersion: v1
kind: Service
metadata:
  name: lmek-D
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "lmek-D"
    port: 8080
  selector:
    app: lmek-D
